name: Bug Report
description: If you think you've found a bug in the machine
title: ":cockroach: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!
        
        We're sorry that you're experiencing an issue. So that we can help you effectively, please fill in this form to the best of your ability. The more information that you can provide the easier we will be able to help you.
                
        **Helpful Links**
        - [Code of Conduct](https://github.com/projectkeas/.github/blob/main/CODE_OF_CONDUCT.md)
        - [Contribution Guide](https://github.com/projectkeas/.github/blob/main/CONTRIBUTING.md)
        - [Security Guide](https://github.com/projectkeas/.github/blob/main/SECURITY.md)
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please could you provide clearly ordered steps to reproduce the issue
      placeholder: |
        1. Login to the system
        2. Click the menu item
        3. Submit
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else?
      description: Anything else that we should know about your issue?
      placeholder: |
        eg: System information, version information
    validations:
      required: false
